# Generated by Django 2.2.1 on 2019-06-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='intrested',
            new_name='interested',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
    ]
